export default function getAllProducts() {
  return [
    {
      id: "1",
      slug: "dior-star-platform-sneaker-womens",
      name: "Dior Star Platform Sneaker",
      category: "Women's",
      price: 17_500_000,
      stock: 100,
      imageUrl: "https://assets.christiandior.com/is/image/diorprod/KCK413CLDS19W_E03-1?$default_GHC_1080$&crop=377,713,1249,825&bfc=on&qlt=85",
      description: `The Dior Star sneaker enhances the hallmark line with a modern style. Crafted in white calfskin, the upper is accented by a tonal suede calfskin panel on the front, as well as the black CD signature and star on the sides. Completed by a thick, ultralightweight signature sole, the sneaker can be paired with laid-back outfits throughout the year.`,
    },
    {
      id: "2",
      slug: "dior-b44-blade-sneaker-mens",
      name: "B44 Blade Sneaker",
      category: "Men's",
      price: 23_000_000,
      stock: 10,
      imageUrl: "https://assets.christiandior.com/is/image/diorprod/3SN306ZZYH080_E03-1?$default_GHC_1080$&crop=301,740,1409,790&bfc=on&qlt=85",
      description: `The B44 Blade sneaker is characterized by a boldly voluminous silhouette inspired by the 2000s. Constructed in white technical mesh, it features tonal technical fabric panels and a contrasting Blade insert on the sole that references the running universe. The top, heel and sides are accented by the Dior signature. Completed by two-tone laces and a support sock that emphasizes its athletic aesthetic, the sneaker will elevate casual looks with an ultramodern touch.`,
    },
    {
      id: "003",
      slug: "dior-archives-labels-t-shirt-relaxed-fit-mens",
      name: "Dior Archives Labels T-Shirt, Relaxed Fit",
      category: "Men's",
      price: 16_000_000,
      stock: 70,
      imageUrl: "https://assets.christiandior.com/is/image/diorprod/513J696A0677C980_E01?$default_GHC_1080$&crop=413,148,1175,1353&bfc=on&qlt=85",
      description: `The T-shirt features a Dior Archives Labels signature with a 3D-printed variation on the House's tags. Crafted in white cotton jersey, it is distinguished by a flocked signature on the chest and relaxed fit. The T-shirt will be a perfect match for wide-leg Bermuda shorts.`,
    },
    {
      id: "004",
      slug: "small-dior-caro-backpack-womens",
      name: "Small Dior Caro Backpack",
      category: "Women's",
      price: 61_000_000,
      stock: 900,
      imageUrl: "https://assets.christiandior.com/is/image/diorprod/M6302UNOZM413_E01?$default_GHC_1080$&crop=409,223,1167,1663&bfc=on&qlt=85",
      description: `New for Cruise 2025, the Dior Caro backpack embodies modern and elegant style. Crafted in powder pink lambskin elevated by Macrocannage topstitching, the design features a flap adorned with an antique gold-finish metal CD signature that opens to reveal a drawstring main compartment, while a small flap pocket can hold all the essentials. The small backpack has a gold-finish handle and adjustable straps for added comfort.`,
    },
    {
      id: "005",
      slug: "dior-8-belt-bag-mens",
      name: "Dior 8 Belt Bag",
      category: "Men's",
      price: 38_000_000,
      stock: 30,
      imageUrl: "https://assets.christiandior.com/is/image/diorprod/1EIBO071YKYH03E_E01?$default_GHC_1080$&crop=48,989,1890,823&bfc=on&qlt=85",
      description: `New for Spring 2025, the Dior 8 belt bag is a modern and practical creation. Crafted in black Dior Oblique jacquard, it features a flap pocket embellished with a Dior 8 buckle on the front. The zip compartment can hold all the essentials, while the adjustable leather strap allows it to be worn around the waist or crossbody.`,
    },
    {
      id: "006",
      slug: "cannage-cardigan-womens",
      name: "Cannage Cardigan",
      category: "Women's",
      price: 54_000_000,
      stock: 0,
      imageUrl: "https://assets.christiandior.com/is/image/diorprod/514G14A3400X0200_E01?$default_GHC_1080$&crop=329,150,1342,1393&bfc=on&qlt=85",
      description: `The cardigan showcases the iconic Cannage motif. The ecru blended wool and cashmere textured knit design features a button closure and the tonal Christian Dior Paris signature on the back. The cardigan will complete any casual outfit from the season.`,
    },
    {
      id: "007",
      slug: "cd-icon-zipped-coin-purse-mens",
      name: "CD Icon Zipped Coin Purse",
      category: "Men's",
      price: 10_500_000,
      stock: 20,
      imageUrl: "https://assets.christiandior.com/is/image/diorprod/2ESBC316CDIH00N_E01?$default_GHC_1080$&crop=513,1154,969,665&bfc=on&qlt=85",
      description: `The zipped coin purse is a practical piece with refined charm. Crafted in black grained calfskin, it is embellished with a CD Icon signature on the front. The interior features four card slots, two gusseted coin compartments and a central top slot for receipts and bills. The elegant coin purse will easily slip into any pocket.`,
    },
    {
      id: "008",
      slug: "miss-caro-mini-bag-womens",
      name: "Miss Caro Mini Bag",
      category: "Women's",
      price: 54_000_000,
      stock: 0,
      imageUrl: "https://assets.christiandior.com/is/image/diorprod/S5169UDAXM413_E01?$default_GHC_1080$&crop=322,867,1301,934&bfc=on&qlt=85",
      description: `The Miss Caro mini bag enhances the Dior Caro line with modern and timeless elegance. Crafted in powder pink lambskin, it stands out with the unique quilted effect of Macrocannage stitching, as well as a flap accented by a gold-finish metal CD twist clasp inspired by the seal of a Christian Dior perfume bottle. Alternating between gold-finish metal links and tonal enamel links that match the leather, the adjustable chain shoulder strap has a leather insert for added comfort when carrying the bag by hand, wearing it over the shoulder or crossbody.`,
    },
  ];
}

